# Generated by Django 6.0.3 on 2026-03-19 19:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_icd10', models.CharField(max_length=10, unique=True)),
                ('denumire', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('medic', 'Medic'), ('asistenta', 'Asistenta')], default='medic', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('simptome', models.TextField(blank=True)),
                ('examen_clinic', models.TextField(blank=True)),
                ('tratament', models.TextField(blank=True)),
                ('observatii', models.TextField(blank=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultatii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticConsultatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('principal', 'Principal'), ('secundar', 'Secundar')], default='principal', max_length=20)),
                ('consultatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienti.consultatie')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacienti.diagnostic')),
            ],
            options={
                'unique_together': {('consultatie', 'diagnostic')},
            },
        ),
        migrations.AddField(
            model_name='consultatie',
            name='diagnostice',
            field=models.ManyToManyField(blank=True, through='pacienti.DiagnosticConsultatie', to='pacienti.diagnostic'),
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('data_nastere', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresa', models.TextField(blank=True)),
                ('grup_sangvin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('0+', '0+'), ('0-', '0-')], max_length=3)),
                ('alergii', models.TextField(blank=True)),
                ('data_inregistrare', models.DateField(auto_now_add=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacienti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nume', 'prenume'],
            },
        ),
        migrations.AddField(
            model_name='consultatie',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultatii', to='pacienti.pacient'),
        ),
    ]
