# Generated by Django 6.0.3 on 2026-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='status',
            field=models.CharField(choices=[('activ', 'Activ'), ('decedat', 'Decedat'), ('transferat', 'Transferat la alt medic'), ('inactiv', 'Inactiv')], default='activ', max_length=20),
        ),
    ]
