# Generated by Django 6.0.3 on 2026-03-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0002_pacient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('durata_min', models.PositiveIntegerField(default=20)),
                ('motiv', models.CharField(blank=True, max_length=255)),
                ('nume_pacient', models.CharField(blank=True, max_length=100)),
                ('telefon_pacient', models.CharField(blank=True, max_length=20)),
                ('email_pacient', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('programat', 'Programat'), ('confirmat', 'Confirmat'), ('anulat', 'Anulat'), ('finalizat', 'Finalizat')], default='programat', max_length=20)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programari', to=settings.AUTH_USER_MODEL)),
                ('pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programari', to='pacienti.pacient')),
            ],
            options={
                'ordering': ['data_ora'],
            },
        ),
    ]
