# Generated by Django 6.0.3 on 2026-03-28 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0006_concediumedical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concediumedical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuratiecabinet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liniereteta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Trimitere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_trimitere', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_emiterii', models.DateField(auto_now_add=True)),
                ('valabilitate_zile', models.IntegerField(default=30)),
                ('specialist', models.CharField(choices=[('cardiologie', 'Cardiologie'), ('neurologie', 'Neurologie'), ('oftalmologie', 'Oftalmologie'), ('ortopedie', 'Ortopedie'), ('dermatologie', 'Dermatologie'), ('ginecologie', 'Ginecologie'), ('urologie', 'Urologie'), ('gastroenterologie', 'Gastroenterologie'), ('endocrinologie', 'Endocrinologie'), ('psihiatrie', 'Psihiatrie'), ('pneumologie', 'Pneumologie'), ('reumatologie', 'Reumatologie'), ('nefrologie', 'Nefrologie'), ('hematologie', 'Hematologie'), ('oncologie', 'Oncologie'), ('chirurgie', 'Chirurgie'), ('ORL', 'ORL'), ('stomatologie', 'Stomatologie'), ('recuperare', 'Recuperare medicala'), ('altele', 'Altele')], max_length=50)),
                ('specialist_custom', models.CharField(blank=True, max_length=100)),
                ('unitate_medicala', models.CharField(blank=True, max_length=200)),
                ('diagnostic', models.CharField(blank=True, max_length=500)),
                ('cod_diagnostic', models.CharField(blank=True, max_length=10)),
                ('investigatii_solicitate', models.TextField(blank=True)),
                ('prioritate', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('nr_fisa', models.CharField(blank=True, max_length=50)),
                ('observatii', models.TextField(blank=True)),
                ('consultatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trimiteri', to='pacienti.consultatie')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trimiteri_emise', to=settings.AUTH_USER_MODEL)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimiteri', to='pacienti.pacient')),
            ],
            options={
                'verbose_name': 'Trimitere',
                'verbose_name_plural': 'Trimiteri',
                'ordering': ['-data_emiterii', '-id'],
            },
        ),
    ]
