# Generated by Django 6.0.3 on 2026-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0007_alter_concediumedical_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod_medic',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parafa',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
