# Generated by Django 6.0.3 on 2026-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0008_customuser_cod_medic_customuser_parafa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('medic', 'Medic'), ('asistent', 'Asistent'), ('superadmin', 'Superadmin'), ('pacient', 'Pacient')], default='medic', max_length=20),
        ),
    ]
