# Generated by Django 6.0.3 on 2026-04-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0009_alter_customuser_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleUtilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
