# Generated by Django 6.0.3 on 2026-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0010_moduleutilizator'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratiecabinet',
            name='durata_slot',
            field=models.PositiveIntegerField(default=30, verbose_name='Durată slot programare (min)'),
        ),
        migrations.AddField(
            model_name='configuratiecabinet',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email contact support'),
        ),
        migrations.AddField(
            model_name='configuratiecabinet',
            name='max_programari_zi',
            field=models.PositiveIntegerField(default=20, verbose_name='Max programări per zi'),
        ),
        migrations.AddField(
            model_name='configuratiecabinet',
            name='mod_mentenanta',
            field=models.BooleanField(default=False, verbose_name='Mod mentenanță'),
        ),
    ]
