# Generated by Django 6.0.3 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0011_configuratiecabinet_durata_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratiecabinet',
            name='orar_saptamanal',
            field=models.JSONField(blank=True, default=dict, help_text='Orar per zi: {luni: {activ, intervale: [{start, end}]}}'),
        ),
    ]
