# Generated by Django 6.0.3 on 2026-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0012_add_orar_saptamanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuratiecabinet',
            name='denumire_unitate',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denumire unitate sanitară'),
        ),
        migrations.AlterField(
            model_name='configuratiecabinet',
            name='judet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Județul'),
        ),
        migrations.AlterField(
            model_name='configuratiecabinet',
            name='localitate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localitatea'),
        ),
    ]
