# Generated by Django 6.0.3 on 2026-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0021_documentpacient_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimitere',
            name='analize_selectate',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='logactivitate',
            name='actiune',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('creare_pacient', 'Creare pacient'), ('modificare_pacient', 'Modificare pacient'), ('stergere_pacient', 'Ștergere pacient'), ('creare_consultatie', 'Creare consultație'), ('creare_reteta', 'Creare rețetă'), ('creare_trimitere', 'Creare trimitere'), ('creare_concediu', 'Creare concediu medical'), ('aprobare_cerere', 'Aprobare cerere pacient'), ('respingere_cerere', 'Respingere cerere pacient'), ('export_xml', 'Export XML CNAS'), ('upload_document', 'Upload document pacient'), ('stergere_document', 'Ștergere document pacient'), ('import_pacienti', 'Import Excel pacienți'), ('creare_user', 'Creare utilizator'), ('stergere_user', 'Ștergere utilizator'), ('creare_programare', 'Creare programare'), ('modificare_programare', 'Modificare programare')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trimitere',
            name='specialist',
            field=models.CharField(choices=[('cardiologie', 'Cardiologie'), ('neurologie', 'Neurologie'), ('oftalmologie', 'Oftalmologie'), ('ortopedie', 'Ortopedie'), ('dermatologie', 'Dermatologie'), ('ginecologie', 'Ginecologie'), ('urologie', 'Urologie'), ('gastroenterologie', 'Gastroenterologie'), ('endocrinologie', 'Endocrinologie'), ('psihiatrie', 'Psihiatrie'), ('pneumologie', 'Pneumologie'), ('reumatologie', 'Reumatologie'), ('nefrologie', 'Nefrologie'), ('hematologie', 'Hematologie'), ('oncologie', 'Oncologie'), ('chirurgie', 'Chirurgie'), ('ORL', 'ORL'), ('stomatologie', 'Stomatologie'), ('recuperare', 'Recuperare medicala'), ('analize_laborator', 'Analize laborator'), ('altele', 'Altele')], max_length=50),
        ),
    ]
