# Generated by Django 6.0.3 on 2026-05-20 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacienti', '0022_add_analize_selectate_to_trimitere'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='cod_diagnostic',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cod ICD-10'),
        ),
        migrations.CreateModel(
            name='DiagnosticPacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adaugarii', models.DateField(auto_now_add=True)),
                ('tip', models.CharField(choices=[('activ', 'Activ'), ('cronic', 'Cronic'), ('antecedent', 'Antecedent'), ('rezolvat', 'Rezolvat')], default='activ', max_length=20)),
                ('sursa', models.CharField(choices=[('consultatie', 'Consultație'), ('scrisoare', 'Scrisoare medicală'), ('extern', 'Document extern')], default='consultatie', max_length=30)),
                ('observatii', models.TextField(blank=True)),
                ('consultatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostice_dosar', to='pacienti.consultatie')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostice_pacienti', to='pacienti.diagnostic')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostice_adaugate', to=settings.AUTH_USER_MODEL)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostice_pacient', to='pacienti.pacient')),
            ],
            options={
                'verbose_name': 'Diagnostic pacient',
                'verbose_name_plural': 'Diagnostice pacient',
                'ordering': ['-data_adaugarii'],
            },
        ),
    ]
